jackmcdade/weird-wide-webring

sites.js

I use Vim.  Some think that's pretty weird.

Am I weird enough?

---

sites.js

Joining the club

---

sites.js

Adding my wee lil site...
Did I do this right? I'm a pretty quirky guy, if you further evidence, check out this blog post from a few years ago: https://davidalindahl.com/posts/2016/06/an-intentional-digital-disconnection/

Adding a little more weirdo-ness

---

index.html

I really hope I'm weird enough, my self-worth and value as a human depends on it.  Just because I can't seem to pry the cold dead tentacles of Albany off of my life like you did, doesn't mean I'm not weird.  Maybe it means I'm more weird?

Weird Wide Webring Teevio

---

sites.js

Love this idea. Long live weird Internet nostalgia!

Added Jamie Howard. Long live the weird.

---

sites.js

Gives me all the more reason to start adding some easter eggs in my site
Also, its my birthday ;)

Because it would be fun to join the crowd

---

sites.js

This is my attempt to be part of the cool kids club 🙂

Add David Llop website

---

sites.js

I've known @aarondfrancis since college and if he's doing something weird then I want to be a part of it 😜

Added colindismuke.com

---

sites.js

My personal site has NO IMAGES on the homepage whatsoever, a built-in fake terminal written in vanilla JavaScript (the "find" command is the best (!!), but try and do some other things too) and loads of hard-to-read monospaced font.
I think that's pretty weird.
I mean, I could add a time-travelling DeLorean, a chicken with laser-beam eyes, or a jet-propelled unicorn-shark hybrid. That would be more weird. Maybe one day.

Add rosswintle.uk

---

README.md
links.html
links.json

Add a simple API for the webring links

---

sites.js

My site is pretty much the only place to find original Star Wars art, code, design, and He-Man parodies this side of the Yahoo river.

Added an extra $20 in one of the files... Just for you.

---

sites.js

I've misspelled `weird` so many times this evening...
Hope I make the list!
https://benleivian.com/

🍔 I would like to buy a hamburger.

---

sites.js

Font switcher for those that hate monospace. Weirdly considerate.

Add davesmyth.com

---

sites.js

```
I like ASCII art and monospace fonts
```

Add danny de vries because reasons

---

sites.js

Joining in on the classic web.

Adding blainsmith.com

---

sites.js

Hi!
I am a huge weirdo. I am adding a link to my personal site which contains unique programming projects I have worked on over the last couple decades. I really like what you have built and would love to be included in the project. I have already added the required links to the bottom of my page.
This pull request is also fixing a bug/typo in the sites.js which was resulting in an invalid dictionary of sites. There was a missing comma from the last pull request.
Thank you for your consideration to include me in the weird-wide-webring!
Nate

Add weird site http://linuxdeveloper.io

---

sites.js

Why do I want to be part of this webring? Because I feel I have a weird site that is run by a Canadian geek who writes about tech, and anything else that is on his mind, and tries to be unbiased when writing about it.
I know we all have a bias and we read what we agree with, but when you read a site that tries to be unbiased then you can see how words can be used to manipulate what a story is about.
I have added the webring links to my site (on the sidebar), which I will edit to say I'm part of this webring when I'm part of it.

Add gregoryhammond.ca

---

sites.js

Freshly deployed so will probably improve it in the future, but I hope you find some weird layout choices interesting!

Added my website lorenzobersano.com to the list

---

sites.js

Submitting this because it is pointless, and weird, and you should be careful what you slice open the box with!

BadlyDrawnBen

---

sites.js

Happy belated birthday! 🎉
My webring links can be found here: https://wyattblogs.com/whois
Cheers, Wyatt 👨‍🚀

Updates sites.js

---

sites.js

Add Dennis Mai meta data to sites.js.
The internet was maturing at the same I was. It mirrored the stages of my growth, periods of innocence full of optimism and discovery, with stages of disappointment and disillusionment and acceptance.
I love the nature of our internet, and I want to do my part in keeping it as true and authentic as people really are in real life. To me, that means doing my part and creating real content.
I found inspiration in your website as well as many others. And while I still have a lot to learn, i would be honored to be considered a part of the weird-wide-webring.
-Dennis

Update sites.js with Dennis Mai

---

sites.js

Added my personal portfolio.
I placed it at the bottom but feel free to reorder it however you like in case you approve my submission.
Also; the site is still in development.

Site submission

---

sites.js

new domain with new arcade implementation in HTML5 at https://biebersoft.net/arcade

New game spoof arcade implemented on weird game site

---

sites.js

this website has since changed its domain name from erickdavid.studio to erickdavid.net

updated `erick david`

---

sites.js

Adding kevq.uk

---

sites.js

I believe leihu qualifies as a weird site for a lot of reasons. I post a lot of weird drawings and stories, and I redesign constantly, currently on version 67 in 21 years.

leihu, weird enough?

---

sites.js

It's wierd because I only have a logo and no other design elements and I'm using neocities. Raw html with a few css rules for images and videos. Also I work fulltime as a software engineer out of a trailer.

add chovy.neocities.org

---

sites.js

I wish to be in the Weird Wide Webring since I believe I am weird and crazy enough, and the purpose of my website is to represent this chaos in the best possible way, while trying to be somehow still a bit understandable by the rest of the world.
[tommi.space](https://tommi.space) is the virtual representation of [Tommi](https://tommi.space/about 'About Tommi')’s mind. It is (almost) the only place on the web where I appear. I [deleted all of my social media accounts](https://quitsocialmedia.club) and I convey all of the content I would throw on Instagram/Facebook/Twitter on tommi.space.
I would be proud to be part of this online community, it is so great and clever, but also beautiful!
Best,  
T

Added tommi.space

---

sites.js

request for fLaMEdFury to join the weird wide webring! 🕸

add flamedfury.com :)
